server:
  port: 8080
  servlet:
    context-path: /beer-service

spring:
  application:
    name: BeerService
  cache:
    jcache:
      config: 'classpath:ehcache.xml'
  datasource:
    name: beer-shop-datasource
    url: 'jdbc:postgresql://localhost:5432/beer_shop'
    username: postgres
    password: ENC(j7OC/L6FZI+8d29tRAYsreDkvGb+V/XF)
    hikari:
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  jpa:
    show-sql: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  devtools:
    restart:
      enabled: true
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
  # credentials for this docker image - vromero/activemq-artemis
  artemis:
    user: admin
    password: ENC(j7OC/L6FZI+8d29tRAYsreDkvGb+V/XF)
  flyway:
    enabled: false

jasypt:
  encryptor:
    password: helw4345gr@%#5fgddlo@1


# Enable logging for config troubleshooting
logging:
  level:
    root: INFO
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
#    com:
#      springboot:
#        storedprocedure: DEBUG
#      zaxxer:
#        hikari:
#          HikariConfig: DEBUG

sfg:
  brewery:
    beer-inventory-service-host: 'http://localhost:8082'
